# Generated by Django 2.2.12 on 2021-12-17 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('designation', models.CharField(max_length=80)),
                ('salary', models.IntegerField()),
            ],
        ),
    ]
